version: '2'

linters:
  enable:
    - govet
    - errcheck
    - staticcheck
    - unused
    - gosimple
    - varcheck
    - misspell
    - lll

# see https://golangci-lint.run/usage/configuration/
