# yaml-language-server: $schema=https://golangci-lint.run/jsonschema/golangci.jsonschema.json

version: '2'

linters:
  enable:
    - govet
    - errcheck
    - staticcheck
    - unused
    - misspell
    - lll

# see https://golangci-lint.run/usage/configuration/
