builds:
  - id: taskhop
    main: ./cmd/taskhop
    binary: taskhop
    goos:
      - darwin
      - linux

  - id: taskhop-agent
    main: ./cmd/taskhop-agent
    binary: taskhop-agent
    goos:
      - darwin
      - linux

release:
  extra_files:
    - glob: ./install.sh
  header: |
    # Install
    ```bash
    curl -sL https://github.com/enuesaa/taskhop/releases/download/{{ .Tag }}/install.sh | bash
    ```
