builds:
  - goos:
      - darwin
      - linux

release:
  extra_files:
    - glob: ./install.sh
  header: |
    # Install
    ```bash
    curl -sL https://github.com/enuesaa/taskhop/releases/download/{{ .Tag }}/install.sh | bash
    mv taskhop /usr/local/bin/taskhop
    ```
