// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package repository

// Injectors from wire.go:

func New() Repos {
	fsRepository := newFsRepository()
	cmdRepository := newCmdRepository()
	repos := newRepos(fsRepository, cmdRepository)
	return repos
}

// wire.go:

func newCmdRepository() CmdRepository {
	return CmdRepository{}
}

func newFsRepository() FsRepository {
	return FsRepository{}
}

func newRepos(fs FsRepository, cmd CmdRepository) Repos {
	return Repos{
		Fs:  &fs,
		Cmd: &cmd,
	}
}
