// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package repository

// Injectors from wire.go:

func New() Repos {
	fsRepository := newFsRepository()
	cmdRepository := newCmdRepository()
	repos := newRepos(fsRepository, cmdRepository)
	return repos
}
