// Code generated by github.com/Yamashou/gqlgenc, DO NOT EDIT.

package client

import (
	"context"

	"github.com/Yamashou/gqlgenc/clientv2"
)

type GraphQLClient interface {
	GetHealth(ctx context.Context, interceptors ...clientv2.RequestInterceptor) (*GetHealth, error)
}

type Client struct {
	Client *clientv2.Client
}

func NewClient(cli clientv2.HttpClient, baseURL string, options *clientv2.Options, interceptors ...clientv2.RequestInterceptor) GraphQLClient {
	return &Client{Client: clientv2.NewClient(cli, baseURL, options, interceptors...)}
}

type GetHealth_Health struct {
	Ok bool "json:\"ok\" graphql:\"ok\""
}

func (t *GetHealth_Health) GetOk() bool {
	if t == nil {
		t = &GetHealth_Health{}
	}
	return t.Ok
}

type GetHealth struct {
	Health GetHealth_Health "json:\"health\" graphql:\"health\""
}

func (t *GetHealth) GetHealth() *GetHealth_Health {
	if t == nil {
		t = &GetHealth{}
	}
	return &t.Health
}

const GetHealthDocument = `query getHealth {
	health {
		ok
	}
}
`

func (c *Client) GetHealth(ctx context.Context, interceptors ...clientv2.RequestInterceptor) (*GetHealth, error) {
	vars := map[string]any{}

	var res GetHealth
	if err := c.Client.Post(ctx, "getHealth", GetHealthDocument, &res, vars, interceptors...); err != nil {
		if c.Client.ParseDataWhenErrors {
			return &res, err
		}

		return nil, err
	}

	return &res, nil
}

var DocumentOperationNames = map[string]string{
	GetHealthDocument: "getHealth",
}
