// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package schema

type Health struct {
	Time string `json:"time"`
	Ok   bool   `json:"ok"`
	Code string `json:"code"`
}

type Query struct {
}
