name: ci

on:
  push:
    branches:
      - '**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/env
      - run: go install

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/env
      - run: go test ./...

  staticcheck:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/env
      - run: go install honnef.co/go/tools/cmd/staticcheck@latest

      - run: echo '# staticcheck' >> $GITHUB_STEP_SUMMARY
      - run: staticcheck ./... >> $GITHUB_STEP_SUMMARY
