name: ci

on:
  push:
    branches:
      - '**'
  workflow_dispatch:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-24.04
          - os: ubuntu-24.04-arm
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/env

      - run: go install ./cmd/taskhop
      - run: go install ./cmd/taskhop-agent

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/env

      - run: go install github.com/mfridman/tparse@latest
      - run: go test -cover -json ./... > testresult.out
      - run: tparse -file=testresult.out -format markdown >> $GITHUB_STEP_SUMMARY

  golangci:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/env
      - uses: golangci/golangci-lint-action@v8

  gogenerate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/env

      - run: go generate ./...

      - run: |
          if [[ -n "$(git diff --name-only)" ]]; then
            git diff --name-only;
            echo "::error::Uncommitted changes found. Please run go generate";
            exit 1;
          fi
