name: dev

on:
  push:
    branches:
      - '**'
  workflow_dispatch:

jobs:
  dev:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/env
      - run: go install

      - run: |
          nohup taskhop &

      - run: echo a
