name: e2e

on:
  push:
    branches:
      - '**'
  workflow_dispatch:

jobs:
  e2e:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/env

      - run: go install ./cmd/taskhop
      - run: go install ./cmd/taskhop-runner

      - name: Run runner
        working-directory: ./testdata/runner
        run: nohup taskhop-runner -c localhost:3000 &

      - name: Run commander
        run: echo "pwd" | taskhop -w testdata/commander
