name: e2e

on:
  push:
    branches:
      - '**'
  workflow_dispatch:

jobs:
  e2e:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/env
      - run: go install

      - name: Run commander
        run: nohup taskhop -w testdata &

      - name: Run runner
        run: |
          mkdir testdata2;
          cd testdata2;
          taskhop -c localhost:3000
