name: e2e

on:
  push:
    branches:
      - '**'
  workflow_dispatch:

jobs:
  e2e:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/env
      - run: go install

      - name: Run runner
        working-directory: ./testdata/runner
        run: nohup taskhop -c localhost:3000 &

      - name: Run commander
        run: taskhop -w testdata/commander

      # - name: cat runner log
      #   working-directory: ./testdata/runner
      #   run: cat nohup.out