name: release

on:
  push:
    tags:
      - '*'

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/env

      - run: go test ./...

      - name: Generate install.sh
        run: envsubst '${VERSION}' < ./install.template.sh > ./install.sh
        env:
          VERSION: ${{ github.ref_name }}

      - uses: goreleaser/goreleaser-action@v6
        with:
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
