name: release

on:
  push:
    tags:
      - '*'

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/env

      - run: go test ./...

      # strip `v`
      - run: echo "VERSION=${TAG#v}" >> $GITHUB_ENV
        env:
          TAG: ${{ github.ref_name }}
      
      - name: Generate install.sh
        run: envsubst < ./install.template.sh > ./install.sh

      - uses: goreleaser/goreleaser-action@v6
        with:
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
